#!/bin/sh

set -e

usage() {
	echo "usage: $(basename "$0") [-h] [-b base] [-o outfile] infile ..." >&2
	exit 1
}

boptarg=
ooptarg=

while getopts hb:o: ch; do
	case "$ch" in
		b)
			if [ ! -z "$boptarg" ]; then
				usage
			fi
			boptarg="$OPTARG"
			;;
		o)
			if [ ! -z "$ooptarg" ]; then
				usage
			fi
			ooptarg="$OPTARG"
			;;
		*)
			usage
			;;
	esac
done

shift $(($OPTIND - 1))

if [ $# = 0 ]; then
	usage
fi

if [ -z "$boptarg" ]; then
	boptarg=262144
fi

if [ -z "$ooptarg" ]; then
   ooptarg="a.img"
fi

. "$(dirname "$0")/imgld.subr"

include() {
	if [ "${file#*.}" = "scr" ]; then
		scr -r "$file" "$name.blk"
		size=$(wc -c < "$name.blk")
	fi
	img -s $addr -i $size "$ooptarg" < "$name.blk"
	able "$ooptarg" <<EOF | grep -v "^ ok" || true
: $name/ ( u1 - u2)  # $(($addr / 1024)) + ;
bye
EOF
}

imgld include "$boptarg" "$@"
